default:
  server:
    port: 3000
    host: '0.0.0.0'
  database:
    host: '127.0.0.1'
    port: 3306
    connection_pool_size: 10
development:
  database:
    db: '4wheel_love'
    user: 'root'
    password: ''
test:
  database:
    db: 'test_db'
production:
  server:
    port: 8000
  database:
    db: 'prod_db'
    user: 'dbuser'
    password: 'pass'
  cache:
    dir: 'static'
